name: Generate Videos JSON

on:
  push:
    branches:
      - main
    paths:
      - "content/videos/**"
      - ".github/workflows/generate-videos-json.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install gray-matter

      - name: Convert videos to JSON
        run: |
          mkdir -p data
          node scripts/generate-videos-json.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/videos.json
          git commit -m "Update videos.json" || echo "No changes to commit"
          git push
