name: Generate Headlines JSON

on:
  push:
    paths:
      - 'content/headlines/**'
      - 'content/main-headline.md'
      - '.github/workflows/generate-headlines-json.yml'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: generate-headlines-json-main
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Melbourne   # ensure date tools default to Melbourne

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install gray-matter glob

      - name: Sync with remote main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Generate JSON files
        run: node scripts/generate-headlines-json.js

      - name: Normalise dates to YYYY-MM-DD (no timezone)
        env:
          TZ: Australia/Melbourne
        run: |
          fix() {
            f="$1"
            [ -f "$f" ] || return 0
            tmp="$(mktemp)"
            # If an object has a "date", drop everything after the first 'T'
            jq 'walk(
                  if type=="object" and has("date") then
                    .date |= ( . | tostring | sub("T.*$"; "") )
                  else .
                  end
                )' "$f" > "$tmp"
            mv "$tmp" "$f"
          }
          fix data/headlines.json
          fix data/main-headline.json

      - name: Commit and push changes
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/headlines.json data/archive.json data/main-headline.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update headlines and main headline JSON (Melbourne dates)"
          git push origin HEAD:main
