name: Generate Sitemap

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: sitemap-generate
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate sitemap.xml
      run: node scripts/generate-sitemap.js

    - name: Commit and push sitemap.xml
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Update sitemap.xml" || echo "No changes to commit"
        git push
